// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Wages.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Wages.proto</summary>
public static partial class WagesReflection {

  #region Descriptor
  /// <summary>File descriptor for Wages.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static WagesReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgtXYWdlcy5wcm90byIyChBXYWdlQnlTU05SZXF1ZXN0Eh4KFnNvY2lhbF9z",
          "ZWN1cml0eV9udW1iZXIYASABKAkiJAoMV2FnZVJlc3BvbnNlEhQKBVdhZ2Vz",
          "GAEgAygLMgUuV2FnZSJVCgRXYWdlEh4KFnNvY2lhbF9zZWN1cml0eV9udW1i",
          "ZXIYASABKAkSDAoEeWVhchgCIAEoERIPCgdxdWFydGVyGAMgASgREg4KBmFt",
          "b3VudBgEIAEoATJACgtXYWdlU2VydmljZRIxCg1HZXRXYWdlc0J5U1NOEhEu",
          "V2FnZUJ5U1NOUmVxdWVzdBoNLldhZ2VSZXNwb25zZWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::WageBySSNRequest), global::WageBySSNRequest.Parser, new[]{ "SocialSecurityNumber" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::WageResponse), global::WageResponse.Parser, new[]{ "Wages" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Wage), global::Wage.Parser, new[]{ "SocialSecurityNumber", "Year", "Quarter", "Amount" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class WageBySSNRequest : pb::IMessage<WageBySSNRequest>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<WageBySSNRequest> _parser = new pb::MessageParser<WageBySSNRequest>(() => new WageBySSNRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<WageBySSNRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::WagesReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public WageBySSNRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public WageBySSNRequest(WageBySSNRequest other) : this() {
    socialSecurityNumber_ = other.socialSecurityNumber_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public WageBySSNRequest Clone() {
    return new WageBySSNRequest(this);
  }

  /// <summary>Field number for the "social_security_number" field.</summary>
  public const int SocialSecurityNumberFieldNumber = 1;
  private string socialSecurityNumber_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string SocialSecurityNumber {
    get { return socialSecurityNumber_; }
    set {
      socialSecurityNumber_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as WageBySSNRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(WageBySSNRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (SocialSecurityNumber != other.SocialSecurityNumber) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (SocialSecurityNumber.Length != 0) hash ^= SocialSecurityNumber.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (SocialSecurityNumber.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(SocialSecurityNumber);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (SocialSecurityNumber.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(SocialSecurityNumber);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (SocialSecurityNumber.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(SocialSecurityNumber);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(WageBySSNRequest other) {
    if (other == null) {
      return;
    }
    if (other.SocialSecurityNumber.Length != 0) {
      SocialSecurityNumber = other.SocialSecurityNumber;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          SocialSecurityNumber = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          SocialSecurityNumber = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class WageResponse : pb::IMessage<WageResponse>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<WageResponse> _parser = new pb::MessageParser<WageResponse>(() => new WageResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<WageResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::WagesReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public WageResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public WageResponse(WageResponse other) : this() {
    wages_ = other.wages_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public WageResponse Clone() {
    return new WageResponse(this);
  }

  /// <summary>Field number for the "Wages" field.</summary>
  public const int WagesFieldNumber = 1;
  private static readonly pb::FieldCodec<global::Wage> _repeated_wages_codec
      = pb::FieldCodec.ForMessage(10, global::Wage.Parser);
  private readonly pbc::RepeatedField<global::Wage> wages_ = new pbc::RepeatedField<global::Wage>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::Wage> Wages {
    get { return wages_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as WageResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(WageResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!wages_.Equals(other.wages_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= wages_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    wages_.WriteTo(output, _repeated_wages_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    wages_.WriteTo(ref output, _repeated_wages_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    size += wages_.CalculateSize(_repeated_wages_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(WageResponse other) {
    if (other == null) {
      return;
    }
    wages_.Add(other.wages_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          wages_.AddEntriesFrom(input, _repeated_wages_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          wages_.AddEntriesFrom(ref input, _repeated_wages_codec);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class Wage : pb::IMessage<Wage>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Wage> _parser = new pb::MessageParser<Wage>(() => new Wage());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Wage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::WagesReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Wage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Wage(Wage other) : this() {
    socialSecurityNumber_ = other.socialSecurityNumber_;
    year_ = other.year_;
    quarter_ = other.quarter_;
    amount_ = other.amount_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Wage Clone() {
    return new Wage(this);
  }

  /// <summary>Field number for the "social_security_number" field.</summary>
  public const int SocialSecurityNumberFieldNumber = 1;
  private string socialSecurityNumber_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string SocialSecurityNumber {
    get { return socialSecurityNumber_; }
    set {
      socialSecurityNumber_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "year" field.</summary>
  public const int YearFieldNumber = 2;
  private int year_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Year {
    get { return year_; }
    set {
      year_ = value;
    }
  }

  /// <summary>Field number for the "quarter" field.</summary>
  public const int QuarterFieldNumber = 3;
  private int quarter_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Quarter {
    get { return quarter_; }
    set {
      quarter_ = value;
    }
  }

  /// <summary>Field number for the "amount" field.</summary>
  public const int AmountFieldNumber = 4;
  private double amount_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public double Amount {
    get { return amount_; }
    set {
      amount_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Wage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Wage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (SocialSecurityNumber != other.SocialSecurityNumber) return false;
    if (Year != other.Year) return false;
    if (Quarter != other.Quarter) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Amount, other.Amount)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (SocialSecurityNumber.Length != 0) hash ^= SocialSecurityNumber.GetHashCode();
    if (Year != 0) hash ^= Year.GetHashCode();
    if (Quarter != 0) hash ^= Quarter.GetHashCode();
    if (Amount != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Amount);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (SocialSecurityNumber.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(SocialSecurityNumber);
    }
    if (Year != 0) {
      output.WriteRawTag(16);
      output.WriteSInt32(Year);
    }
    if (Quarter != 0) {
      output.WriteRawTag(24);
      output.WriteSInt32(Quarter);
    }
    if (Amount != 0D) {
      output.WriteRawTag(33);
      output.WriteDouble(Amount);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (SocialSecurityNumber.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(SocialSecurityNumber);
    }
    if (Year != 0) {
      output.WriteRawTag(16);
      output.WriteSInt32(Year);
    }
    if (Quarter != 0) {
      output.WriteRawTag(24);
      output.WriteSInt32(Quarter);
    }
    if (Amount != 0D) {
      output.WriteRawTag(33);
      output.WriteDouble(Amount);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (SocialSecurityNumber.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(SocialSecurityNumber);
    }
    if (Year != 0) {
      size += 1 + pb::CodedOutputStream.ComputeSInt32Size(Year);
    }
    if (Quarter != 0) {
      size += 1 + pb::CodedOutputStream.ComputeSInt32Size(Quarter);
    }
    if (Amount != 0D) {
      size += 1 + 8;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Wage other) {
    if (other == null) {
      return;
    }
    if (other.SocialSecurityNumber.Length != 0) {
      SocialSecurityNumber = other.SocialSecurityNumber;
    }
    if (other.Year != 0) {
      Year = other.Year;
    }
    if (other.Quarter != 0) {
      Quarter = other.Quarter;
    }
    if (other.Amount != 0D) {
      Amount = other.Amount;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          SocialSecurityNumber = input.ReadString();
          break;
        }
        case 16: {
          Year = input.ReadSInt32();
          break;
        }
        case 24: {
          Quarter = input.ReadSInt32();
          break;
        }
        case 33: {
          Amount = input.ReadDouble();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          SocialSecurityNumber = input.ReadString();
          break;
        }
        case 16: {
          Year = input.ReadSInt32();
          break;
        }
        case 24: {
          Quarter = input.ReadSInt32();
          break;
        }
        case 33: {
          Amount = input.ReadDouble();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
