// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Wages.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

public static partial class WageService
{
  static readonly string __ServiceName = "WageService";

  static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
  {
    #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
    if (message is global::Google.Protobuf.IBufferMessage)
    {
      context.SetPayloadLength(message.CalculateSize());
      global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
      context.Complete();
      return;
    }
    #endif
    context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
  }

  static class __Helper_MessageCache<T>
  {
    public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
  }

  static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
  {
    #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
    if (__Helper_MessageCache<T>.IsBufferMessage)
    {
      return parser.ParseFrom(context.PayloadAsReadOnlySequence());
    }
    #endif
    return parser.ParseFrom(context.PayloadAsNewBuffer());
  }

  static readonly grpc::Marshaller<global::WageBySSNRequest> __Marshaller_WageBySSNRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::WageBySSNRequest.Parser));
  static readonly grpc::Marshaller<global::WageResponse> __Marshaller_WageResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::WageResponse.Parser));

  static readonly grpc::Method<global::WageBySSNRequest, global::WageResponse> __Method_GetWagesBySSN = new grpc::Method<global::WageBySSNRequest, global::WageResponse>(
      grpc::MethodType.Unary,
      __ServiceName,
      "GetWagesBySSN",
      __Marshaller_WageBySSNRequest,
      __Marshaller_WageResponse);

  /// <summary>Service descriptor</summary>
  public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
  {
    get { return global::WagesReflection.Descriptor.Services[0]; }
  }

  /// <summary>Base class for server-side implementations of WageService</summary>
  [grpc::BindServiceMethod(typeof(WageService), "BindService")]
  public abstract partial class WageServiceBase
  {
    public virtual global::System.Threading.Tasks.Task<global::WageResponse> GetWagesBySSN(global::WageBySSNRequest request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

  }

  /// <summary>Client for WageService</summary>
  public partial class WageServiceClient : grpc::ClientBase<WageServiceClient>
  {
    /// <summary>Creates a new client for WageService</summary>
    /// <param name="channel">The channel to use to make remote calls.</param>
    public WageServiceClient(grpc::ChannelBase channel) : base(channel)
    {
    }
    /// <summary>Creates a new client for WageService that uses a custom <c>CallInvoker</c>.</summary>
    /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
    public WageServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
    {
    }
    /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
    protected WageServiceClient() : base()
    {
    }
    /// <summary>Protected constructor to allow creation of configured clients.</summary>
    /// <param name="configuration">The client configuration.</param>
    protected WageServiceClient(ClientBaseConfiguration configuration) : base(configuration)
    {
    }

    public virtual global::WageResponse GetWagesBySSN(global::WageBySSNRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return GetWagesBySSN(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::WageResponse GetWagesBySSN(global::WageBySSNRequest request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_GetWagesBySSN, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::WageResponse> GetWagesBySSNAsync(global::WageBySSNRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return GetWagesBySSNAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::WageResponse> GetWagesBySSNAsync(global::WageBySSNRequest request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_GetWagesBySSN, null, options, request);
    }
    /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
    protected override WageServiceClient NewInstance(ClientBaseConfiguration configuration)
    {
      return new WageServiceClient(configuration);
    }
  }

  /// <summary>Creates service definition that can be registered with a server</summary>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static grpc::ServerServiceDefinition BindService(WageServiceBase serviceImpl)
  {
    return grpc::ServerServiceDefinition.CreateBuilder()
        .AddMethod(__Method_GetWagesBySSN, serviceImpl.GetWagesBySSN).Build();
  }

  /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
  /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
  /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static void BindService(grpc::ServiceBinderBase serviceBinder, WageServiceBase serviceImpl)
  {
    serviceBinder.AddMethod(__Method_GetWagesBySSN, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::WageBySSNRequest, global::WageResponse>(serviceImpl.GetWagesBySSN));
  }

}
#endregion
